### ISSUE TITLE
`vue-jest` yarn install error

### ISSUE THREAD

**Issue by liaoliaojun** [kkbjs/element3#19]
`vue-jest: vuejs/vue-jest#next` yarn install this version error.

**Comment by cuixiaorui** [comment]
可以尝试用 npm 安装一下

**Comment by cuixiaorui** [comment]
可以尝试用 npm 安装一下

**Comment by cuixiaorui** [comment]
等等

**Comment by cuixiaorui** [comment]
可以尝试用 npm 安装一下

如果还有问题的话可以去 [传送门](https://github.com/vuejs/vue-jest/issues)

**Comment by cuixiaorui** [comment]
可以尝试用 npm 安装一下

如果还有问题的话可以去给这个库提交 issue [传送门](https://github.com/vuejs/vue-jest/issues)

**Comment by cuixiaorui** [comment]
可以尝试用 npm 安装一下

如果还有问题的话可以去给相关库提交 issue [传送门](https://github.com/vuejs/vue-jest/issues)

**Comment by liaoliaojun** [comment]
关键是`vue-jest`根本没有 ' vuejs/vue-jest#next' 这个版本啊，你们是怎么安装上的？ https://www.npmjs.com/package/vue-jest
