### ISSUE TITLE
讨论：$on的替代方案

### ISSUE THREAD

**Issue by yeyuqiudeng** [kkbjs/element3#20]
我看到原来的 `emitter` 已经使用 composition-api 重构，但是 vue3 在组件的实例上已经不存在 `$on` 方法，这就造成了一个比较尴尬的问题，在事件 `dispatch` 或者 `broadcast` 后无法监听。

我想到有三种方式：
1. 使用 provide/eject 来替换现在的 `emitter` 
2. 强行监听，在 `instance.vnode.props` 在设置 `onEventxxx` 的监听方法。
3. 完整实现一个EventEmitter

或者还有其他更好的方式？

我觉得应该尽快将方案确定一下，方便后续贡献代码，毕竟 `emitter` 用到的地方有点多。

**Comment by cuixiaorui** [comment]
先实现了 on 方法

可以基于此来调用
