### ISSUE TITLE
文档 官网markdown文档代码未正确高亮

### ISSUE THREAD

**Issue by tangxiangmin** [kkbjs/element3#208]
### Element UI version
element3 0.0.11

### OS/Browsers version
Mac

### Vue version
^3.0.0-rc.5

### Reproduction Link
![](http://img.shymean.com/oPic/1600182834050_285.png)

可能是移除lock文件后markdown-it某个版本的问题，我能提交一个PR修复配置吗

**Comment by shengxinjing** [comment]
已合并
