### ISSUE TITLE
[Bug Report] 官网地址无法访问——404 

### ISSUE THREAD

**Issue by h7ml** [kkbjs/element3#240]
### Element UI version
2.13.2

### OS/Browsers version
windows

### Vue version
3.0.2

### Reproduction Link
https://github.com/kkbjs/element3

### Steps to reproduce
打开https://element3.vercel.app/ 即可

### What is Expected?
正常访问

### What is actually happening?
404

**Comment by shengxinjing** [comment]
感谢提醒，官网正在找地方重新部署

**Comment by shengxinjing** [comment]
done
