### ISSUE TITLE
重构 Button 组件

### ISSUE THREAD

**Issue by cuixiaorui** [kkbjs/element3#29]
## Tasking

- [x] 解决逻辑报错
- [x] 使用 composition api 重构逻辑
- [x] 更新使用文档
- [ ] 等待 Form 逻辑修改完成

## Comment

- 没有测试 Form 和 Button 之间的逻辑，等重构 Form 表单时需要处理

**Comment by cuixiaorui** [comment]
测试完成

**Comment by 57code** [comment]
Form已完成
