### ISSUE TITLE
重构 Container 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#38]
## Tasking

- [ ] 解决逻辑报错
- [ ] 使用 composition api 重构逻辑
- [ ] 更新使用文档

## Comment

**Comment by ZhangNing-debug** [comment]
尝试一下

**Comment by ZhangNing-debug** [comment]
已pr  
 

- [ x ] 解决逻辑报错

- [ x ]  使用 composition api 重构逻辑
