### ISSUE TITLE
重构 Color 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#39]
## Tasking

- [ ] 解决逻辑报错
- [ ] 使用 composition api 重构逻辑
- [ ] 更新使用文档

## Comment

**Comment by Iecy** [comment]
占坑

**Comment by Mrchangchang** [comment]
没有人吗，我认领了。

**Comment by Mrchangchang** [comment]
color组件为颜色规范，无对应组件，这个issue可以关掉了。
