### ISSUE TITLE
重构 Border 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#41]
## Tasking

- [ ] 解决逻辑报错
- [ ] 使用 composition api 重构逻辑
- [ ] 更新使用文档

## Comment

**Comment by mqycn** [comment]
都别抢，这个是我的了

**Comment by ArrayMage** [comment]
此位置已占坑

**Comment by su37josephxia** [comment]
我怎么没找到这个组件呢 这个应该关闭吧

**Comment by su37josephxia** [comment]
components.json 这个应该是组件列表

**Comment by su37josephxia** [comment]
http://0.0.0.0:8086/#/zh-CN/component/border
![image](https://user-images.githubusercontent.com/9651900/91967214-7cc47e80-ed45-11ea-820f-3000d8ff8348.png)
只是个样式可以直接关掉了
