### ISSUE TITLE
重构 Icon 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#42]
## Tasking

- [x] 解决逻辑报错
- [x] 使用 composition api 重构逻辑
- [x] 更新使用文档

## Comment

**Comment by dengshenkk** [comment]
我即将重构这个组件。doing

**Comment by ImJustAMan** [comment]
> 我即将重构这个组件。doing

其实 已经重构完了的emmmm

**Comment by calcyu** [comment]
文档页demo显示有问题，因为少了一个div所以应用不到`.demo-icon .source > div > i `选择器样式，其实所有组件demo都有这个问题
