### ISSUE TITLE
重构 Input 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#44]
## Tasking

- [x] 解决逻辑报错
- [x] 使用 composition api 重构逻辑
- [x] 更新使用文档
- [ ] 等待 formItem 完成
## Comment

**Comment by ImJustAMan** [comment]
@CharlieLau 此组件还有很多地方没有完善。。建议罗列一下我们更新到tasking中

**Comment by 57code** [comment]
form已完成，可以联调
