### ISSUE TITLE
重构 Select 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#46]
## Tasking

- [ ] 解决逻辑报错
- [ ] 使用 composition api 重构逻辑
- [ ] 更新使用文档

## Comment

**Comment by zanglifeng** [comment]
此位置已有人。

**Comment by 57code** [comment]
已经9天没有代码提交，此组件已收回

**Comment by 57code** [comment]
目前还有搜索、添加条目问题未解决

**Comment by 57code** [comment]
- 等待emmiter改造
- 测试

**Comment by 57code** [comment]
todo: 测试

**Comment by calcyu** [comment]
- [ ] composition api 重构逻辑 

工作量有点大，不要改重了
