### ISSUE TITLE
重构 Switch 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#48]
## Tasking

- [x] 解决逻辑报错
- [x] 使用 composition api 重构逻辑
- [x] 更新使用文档
- [ ] 等待 elFromItem || elFrom 逻辑修改完成

## Comment
- 涉及到关于 elFrom 的逻辑全部被干掉了
- 后面处理 elFromItem || elFrom 的时候在添加对应的逻辑
    - name
    - validate-event
    - focus
    - input 相关逻辑
- 在使用文档里面使用了 el-tooltip ，但是 tooltip 现在有问题 等修好了 tooltip 之后再处理 switch 的不同 value 的类型

**Comment by 57code** [comment]
form已完成，可以联调
