### ISSUE TITLE
重构 ColorPicker 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#55]
## Tasking

- [ ] 解决逻辑报错
- [ ] 使用 composition api 重构逻辑
- [ ] 更新使用文档

## Comment

**Comment by YiJunXing** [comment]
我即将重构这个组件。但个人觉得我比较菜，欢迎一起搞，哈哈哈，重在学习

**Comment by Coiven** [comment]
#166 提了pr才看到这个issue。。。

**Comment by YiJunXing** [comment]
没关系呀，我还在学习呢，动手能力差，刚好我可以看看你提的，向你学习------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;听风吟丶&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月3日(星期四) 晚上6:14
收件人:&nbsp;&quot;kkbjs/element3&quot;<element3@noreply.github.com&gt;;
抄送:&nbsp;&quot;YiJunXing&quot;<2687346406@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [kkbjs/element3] 重构 ColorPicker 组件 (#55)

**Comment by Mrchangchang** [comment]
我在开发这个了，现在只差测试用例了。
