### ISSUE TITLE
重构 Transfer 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#56]
## Tasking

- [ ] 解决逻辑报错
- [ ] 使用 composition api 重构逻辑
- [ ] 更新使用文档

## Comment

**Comment by chimyrabbit** [comment]
1

**Comment by chimyrabbit** [comment]
1

**Comment by lovelyBug** [comment]
我来重构Transfer组件

**Comment by lovelyBug** [comment]
目前基本已完成了 测试用例编写 和  transfer组件的重构，这两天准备提交PR
