### ISSUE TITLE
重构 Tree 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#61]
## Tasking

- [ ] 解决逻辑报错
- [ ] 使用 composition api 重构逻辑
- [ ] 更新使用文档

## Comment

**Comment by chimyrabbit** [comment]
试试

**Comment by WumaCoder** [comment]
终于找到一个没人做的，我太难了😒

**Comment by WumaCoder** [comment]
姓刘了

**Comment by WumaCoder** [comment]
Tree组件已经开发完成并且已经PR，请管理员审核关联
