### ISSUE TITLE
重构 Pagination 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#62]
## Tasking

- [x] 解决逻辑报错
- [x] 使用 composition api 重构逻辑
- [x] 更新使用文档
- [x] 等待select组件完善

## Comment
还差一个选择pageSize的组件 需要select组件支持，其他功能暂以完善

**Comment by shengxinjing** [comment]
注意进度，太慢的话考虑帮忙提交拉

**Comment by zmouse** [comment]
好，这周弄完。其他人也可以帮忙。

**Comment by ImJustAMan** [comment]
> 好，这周弄完。其他人也可以帮忙。

归我了 你可以专心忙loading了[doge]
