### ISSUE TITLE
重构 Loading 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#66]
## Tasking

- [ ] 解决逻辑报错
- [ ] 使用 composition api 重构逻辑
- [ ] 更新使用文档

## Comment

**Comment by xjh1230** [comment]
排个队

**Comment by shengxinjing** [comment]
重新开放占位

**Comment by xjh1230** [comment]
占坑了

**Comment by elven-liang** [comment]
占坑了

**Comment by zhe-he** [comment]
发个呆

**Comment by elven-liang** [comment]
需要组队的话 建个微信群吧 wechat id: i670878721

**Comment by ambitionyu** [comment]
> 需要组队的话 建个微信群吧 wechat id: i670878721

还需要人吗？？我应该可以写简单的和一点测试

**Comment by GeekQiaQia** [comment]
do it

**Comment by elven-liang** [comment]
@shengxinjing 这个可以重新占位了 我们这几个搞不掂

**Comment by beichensky** [comment]
重新占位。

**Comment by AnsonZnl** [comment]
排个队~

**Comment by Ruandou** [comment]
？？？这个提交是啥？都修好了，为什么把我的代码revert掉了？ @cuixiaorui
