### ISSUE TITLE
重构 MessageBox 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#68]
## Tasking

- [ ] 解决逻辑报错
- [ ] 使用 composition api 重构逻辑
- [ ] 更新使用文档

## Comment

**Comment by shengxinjing** [comment]
重新开放占位

**Comment by ArrayMage** [comment]
占坑～

**Comment by wulinsheng123** [comment]
占坑

**Comment by wulinsheng123** [comment]
> 占坑

https://github.com/wulinsheng123/element3/pull/3

**Comment by wulinsheng123** [comment]
[合并代码](https://github.com/wulinsheng123/element3/pull/3)

**Comment by wulinsheng123** [comment]
update #wulinsheng123  #3

**Comment by wulinsheng123** [comment]
fix #47

**Comment by wulinsheng123** [comment]
进度40%

**Comment by wulinsheng123** [comment]
进度65%，缺少modal

**Comment by wulinsheng123** [comment]
70%解决一些bug

**Comment by wulinsheng123** [comment]
> 70%解决一些bug

还差最后的校验，预计这周内完成
