### ISSUE TITLE
重构 NavMenu 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#70]
## Tasking

- [ ] 解决逻辑报错
- [x] 使用 composition api 重构逻辑
- [x] 更新使用文档

## Comment

**Comment by liugang1988** [comment]
占个坑

**Comment by zhouswsky100** [comment]
> ## Tasking
> * [ ]  解决逻辑报错
> * [ ]  使用 composition api 重构逻辑
> * [ ]  更新使用文档
> 
> ## Comment

我来搞
