### ISSUE TITLE
重构 Tabs 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#71]
## Tasking

- [ ] 解决逻辑报错
- [ ] 使用 composition api 重构逻辑
- [ ] 更新使用文档

## Comment

**Comment by GitHubForQiuKai** [comment]
此组件已姓仇

**Comment by dengshenkk** [comment]
我来重构这个组件

**Comment by GeekQiaQia** [comment]
coding

**Comment by shengxinjing** [comment]
组件收回，我占了

**Comment by GeekQiaQia** [comment]
> 组件收回，我占了

按原先的逻辑，通过slots获取组件实例那里，不知道怎么处理了，期待view学习大圣老师的代码

**Comment by shengxinjing** [comment]
@GeekQiaQia 你如果有可以演示的代码的话，可以pr提交一个，说明代码实现的功能合缺陷，我帮你不全剩下的也可以

**Comment by GeekQiaQia** [comment]
> @GeekQiaQia 你如果有可以演示的代码的话，可以pr提交一个，说明代码实现的功能合缺陷，我帮你不全剩下的也可以

嗯 好的，我再看看，按照原先的逻辑，我现在是获取不到pane实例，所以显示不出来tab-nav以及处理nav相关的逻辑；

**Comment by GeekQiaQia** [comment]
> @GeekQiaQia 你如果有可以演示的代码的话，可以pr提交一个，说明代码实现的功能合缺陷，我帮你不全剩下的也可以
大圣老师，tabs中 watch currentName中有一个调用子组件方法，不知道怎么处理比较好；
 * 有想过通过emmiter事件的方式通知执行；但是没有on事件中没有执行函数
pr:
bug: tabs中$refs.nav.scrollToActiveTab()相关处理,

**Comment by GeekQiaQia** [comment]
> @GeekQiaQia 你如果有可以演示的代码的话，可以pr提交一个，说明代码实现的功能合缺陷，我帮你不全剩下的也可以
大圣老师，tabs组件改完了。
测试用例，没有补充完，我回头试试；
