### ISSUE TITLE
重构 Card 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#79]
## Tasking

- [ ] 解决逻辑报错
- [ ] 使用 composition api 重构逻辑
- [ ] 更新使用文档

## Comment

**Comment by su37josephxia** [comment]
这个Card我来改

**Comment by shengxinjing** [comment]
重新开放占位

**Comment by cdhhhhhhh** [comment]
这个我接了

**Comment by jiameng15** [comment]
先改为敬

**Comment by mqycn** [comment]
> 先改为敬

这个状态标错了，su37josephxia 的代码已经合并了：https://github.com/kkbjs/element3/tree/master/packages/card
