### ISSUE TITLE
重构 Collapse 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#81]
## Tasking

- [ ] 解决逻辑报错
- [ ] 使用 composition api 重构逻辑
- [ ] 更新使用文档

## Comment

**Comment by bcy7758521** [comment]
不停 想试试

**Comment by shawnwangzZ** [comment]
占一个组件

**Comment by iamhmx** [comment]
兄弟弄完没，要不我试试

**Comment by shawnwangzZ** [comment]
pr了，还要写一下test。可以请你帮看看问题，一起参与 @iamhmx

**Comment by shengxinjing** [comment]
@shawnwangzZ pr里记得关联一下这个issue ，这样好找一些

**Comment by Mrchangchang** [comment]
这个组件已经合并进去了，这个issue可以关闭了
