### ISSUE TITLE
重构 Timeline 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#82]
## Tasking

- [ ] 解决逻辑报错
- [ ] 使用 composition api 重构逻辑
- [ ] 更新使用文档

## Comment

**Comment by DanDan1924** [comment]
此组件姓吴

**Comment by WumaCoder** [comment]
被抢了😅

**Comment by DanDan1924** [comment]
> 被抢了😅
???

**Comment by DanDan1924** [comment]
> 被抢了😅

我已经在改了

**Comment by WumaCoder** [comment]
加油，我去做tree

**Comment by DanDan1924** [comment]
> 加油，我去做tree

共勉，哈哈

**Comment by WumaCoder** [comment]
tree有亿点复杂

**Comment by su37josephxia** [comment]
这个组件 6天还没有提交的音信 我提交了
https://github.com/kkbjs/element3/pull/156
