### ISSUE TITLE
重构 Calendar 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#84]
## Tasking

- [ ] 解决逻辑报错
- [ ] 使用 composition api 重构逻辑
- [ ] 更新使用文档

## Comment

**Comment by feibingbalabala** [comment]
我来攻占这个组件

**Comment by su37josephxia** [comment]
我看长时间 没有人提交 我提交了 这里面主要的问题都是scope插槽的修改 我这已经完全OK了 
这个地方让我来

**Comment by GeekQiaQia** [comment]
啊 我写好啦

**Comment by GeekQiaQia** [comment]
> 我看长时间 没有人提交 我提交了 这里面主要的问题都是scope插槽的修改 我这已经完全OK了
> 这个地方让我来

夏老师，给我个机会吧😄

**Comment by su37josephxia** [comment]
你先来  如果插槽那部分不行的话 先merge你那个 我来给你补充上

**Comment by GeekQiaQia** [comment]
> 你先来 如果插槽那部分不行的话 先merge你那个 我来给你补充上 加油⛽️

老师，vue3中slots那里我不知道怎么处理，你帮我补充一下吧，我view你的代码

**Comment by su37josephxia** [comment]
OK  我从你的分支搞 你的这次PR也是成功的
