### ISSUE TITLE
重构 Drawer 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#87]
## Tasking

- [x] 解决逻辑报错
- [x] 使用 composition api 重构逻辑
- [x] 更新使用文档

## Comment

**Comment by amadeus711** [comment]
预计明天提交~

**Comment by amadeus711** [comment]
已重构完毕，正在解决部分共用逻辑报错问题

**Comment by amadeus711** [comment]
已重构完毕，正在解决组件内逻辑bug

**Comment by wxy0902** [comment]
这个组件已经merge了。

**Comment by amadeus711** [comment]
> 这个组件已经merge了。

哇，有点难受，那个右上角不能关闭的bug我找了好久，原来是使用的问题。。。哎，可惜了

**Comment by wxy0902** [comment]
> > 这个组件已经merge了。
> 
> 哇，有点难受，那个右上角不能关闭的bug我找了好久，原来是使用的问题。。。。，可惜了

是的  我也被坑了很久
