### ISSUE TITLE
重构 Image 组件

### ISSUE THREAD

**Issue by ImJustAMan** [kkbjs/element3#88]
## Tasking

- [ ] 解决逻辑报错
- [ ] 使用 composition api 重构逻辑
- [ ] 更新使用文档

## Comment

**Comment by shengxinjing** [comment]
注意进度，太慢的话考虑帮忙提交拉

**Comment by mqycn** [comment]
> 此组件已姓韩.

还做吗，排队抢坑中。。。

**Comment by mqycn** [comment]
没弃坑，预计 明天PR。

**Comment by mqycn** [comment]
Ruandou 的代码已经合并，我在他的基础上重新改。

**Comment by mqycn** [comment]
@shengxinjing 大圣怎么把这个关了，我还在开发中。
