### ISSUE TITLE
运行npm run deploy:build存在压缩的时候问题

### ISSUE THREAD

**Issue by su37josephxia** [kkbjs/element3#95]
![image](https://user-images.githubusercontent.com/9651900/91114672-0677aa80-e6bb-11ea-9583-75dd8259f18b.png)
目前运行版本Node.js v14.7.0.

**Comment by zhe-he** [comment]
https://github.com/kkbjs/element3/pull/112

**Comment by cuixiaorui** [comment]
整个 build 流程会重新设计
